// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hiwork.proto

package hiwork

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/protobuf/types/known/anypb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PingBody) Validate() error {
	if this.Message != nil {
		if !(len(*(this.Message)) > 2) {
			return github_com_mwitkow_go_proto_validators.FieldError("Message", fmt.Errorf(`value '%v' must have a length greater than '2'`, *(this.Message)))
		}
		if !(len(*(this.Message)) < 10) {
			return github_com_mwitkow_go_proto_validators.FieldError("Message", fmt.Errorf(`value '%v' must have a length smaller than '10'`, *(this.Message)))
		}
	}
	return nil
}
func (this *AnyData) Validate() error {
	if this.Params != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(*(this.Params))); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Params", err)
		}
	}
	return nil
}
func (this *AnyData_Param) Validate() error {
	for _, item := range this.Param {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Param", err)
		}
	}
	return nil
}
func (this *AnyData2) Validate() error {
	if this.Params != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(*(this.Params))); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Params", err)
		}
	}
	return nil
}
func (this *AnyData2_Param) Validate() error {
	return nil
}
