<<<<<<< HEAD:cmd/testcase/protocol/go/header.validator.pb.go
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: header.proto

package protocol

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ReqHeader) Validate() error {
	return nil
}
func (this *RespHeader) Validate() error {
	return nil
}
=======
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: header.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ReqHeader) Validate() error {
	return nil
}
func (this *RespHeader) Validate() error {
	return nil
}
>>>>>>> 4aad3e1b64427d5ebafb07f037b140f7eb3a6511:sample/server/internal/grpc/protocol/go/header.validator.pb.go
